name             'dnf-automatic'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
source_url       'https://github.com/osuosl-cookbooks/dnf-automatic'
issues_url       'https://github.com/osuosl-cookbooks/dnf-automatic/issues'
license          'Apache-2.0'
chef_version     '>= 14.0'
description      'Installs/Configures dnf-automatic'
long_description 'Installs/Configures dnf-automatic'
version          '1.0.0'

supports         'centos', '~> 8.0'
