name             'dnf-automatic'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
source_url       'https://github.com/osuosl-cookbooks/dnf-automatic'
issues_url       'https://github.com/osuosl-cookbooks/dnf-automatic/issues'
license          'Apache-2.0'
chef_version     '>= 18.0'
description      'Installs/Configures dnf-automatic'
version          '2.0.8'

depends 'osl-resources'

supports 'almalinux', '~> 8.0'
supports 'almalinux', '~> 9.0'
supports 'almalinux', '~> 10.0'
