require_relative '../../spec_helper'

STEP_INTO = %w(dnf_automatic dnf_automatic_policy dnf_automatic_apply dnf_automatic_test_nested).freeze
MODE_TIMERS = %w(dnf-automatic-download.timer dnf-automatic-install.timer dnf-automatic-notifyonly.timer).freeze
CONF = '/etc/dnf/automatic.conf'.freeze

describe 'dnf_automatic' do
  ALL_PLATFORMS.each do |p|
    el = p[:version].to_i

    context "#{p[:platform]} #{p[:version]}" do
      context 'default' do
        cached(:chef_run) do
          converge_delayed(ChefSpec::SoloRunner.new(p.merge(step_into: STEP_INTO)).converge('dnf-automatic-test::default'))
        end

        it { expect { chef_run }.to_not raise_error }
        it { expect(chef_run).to configure_dnf_automatic('default') }
        it { expect(chef_run).to install_package('dnf-automatic') }
        it { expect(chef_run).to create_template(CONF).with(cookbook: 'dnf-automatic', source: 'automatic.conf.erb') }

        [
          /^# This file was generated by .+$/,
          /^\[commands\]\nupgrade_type = default\nrandom_sleep = 0\nnetwork_online_timeout = 60\ndownload_updates = yes\napply_updates = yes\n/,
          /^\[emitters\]\nemit_via = email\n/,
          /^\[email\]\nemail_from = root@example.org\nemail_to = dnf-automatic@example.org\nemail_host = localhost\n/,
          /^\[command_email\]\nemail_from = root@example.org\nemail_to = root\n/,
          /^\[base\]\ndebuglevel = 1\n\z/,
        ].each do |line|
          it { expect(chef_run).to render_file(CONF).with_content(line) }
        end

        it { expect(chef_run).to_not render_file(CONF).with_content(/^exclude/) }
        it { expect(chef_run).to_not render_file(CONF).with_content(/^system_name/) }
        it { expect(chef_run).to_not render_file(CONF).with_content(/^reboot_command/) }

        if el >= 9
          it { expect(chef_run).to render_file(CONF).with_content(/^apply_updates = yes\nreboot = never\n/) }
          it { expect(chef_run).to render_file(CONF).with_content(/^emit_via = email\nsend_error_messages = no\n/) }
          it { expect(chef_run).to render_file(CONF).with_content(/^email_host = localhost\nemail_port = 25\n/) }
        else
          it { expect(chef_run).to_not render_file(CONF).with_content(/^(reboot|send_error_messages|email_port|email_tls) /) }
        end

        if el >= 10
          it { expect(chef_run).to render_file(CONF).with_content(/^email_port = 25\nemail_tls = no\n/) }
        else
          it { expect(chef_run).to_not render_file(CONF).with_content(/^email_tls/) }
        end

        it do
          expect(chef_run).to create_osl_systemd_unit_drop_in('dnf-automatic').with(
            override_name: 'osuosl',
            unit_name: 'dnf-automatic.timer',
            content: <<~EOF
              [Timer]
              OnCalendar=
              OnCalendar=*-*-* 10:10 US/Pacific
              RandomizedDelaySec=15m
            EOF
          )
        end
        it { expect(chef_run).to enable_service('dnf-automatic.timer') }
        it { expect(chef_run).to start_service('dnf-automatic.timer') }

        MODE_TIMERS.each do |timer|
          it { expect(chef_run).to stop_service(timer) }
          it { expect(chef_run).to disable_service(timer) }
        end
      end

      context 'disabled by a policy' do
        cached(:chef_run) do
          converge_delayed(ChefSpec::SoloRunner.new(p.merge(step_into: STEP_INTO)).converge('dnf-automatic-test::disabled'))
        end

        it { expect(chef_run).to add_dnf_automatic_policy('maintenance').with(enabled: false) }
        it { expect(chef_run).to create_template(CONF) }
        it { expect(chef_run).to stop_service('dnf-automatic.timer') }
        it { expect(chef_run).to disable_service('dnf-automatic.timer') }
        it { expect(chef_run).to_not start_service('dnf-automatic.timer') }
      end

      context 'policies around the baseline' do
        cached(:chef_run) do
          converge_delayed(ChefSpec::SoloRunner.new(p.merge(step_into: STEP_INTO)).converge('dnf-automatic-test::policy'))
        end

        if el >= 9
          it { expect(chef_run).to add_dnf_automatic_policy('early') }
          it { expect(chef_run).to add_dnf_automatic_policy('late') }
          it { expect(chef_run).to add_dnf_automatic_policy('nested').with(exclude: %w(postgresql*)) }
          it { expect(chef_run).to_not add_dnf_automatic_policy('guarded') }

          [
            /^upgrade_type = security$/,
            /^download_updates = yes\napply_updates = no\nreboot = when-needed$/,
            /^send_error_messages = yes$/,
            /^exclude = mariadb\* postgresql\*$/,
          ].each do |line|
            it { expect(chef_run).to render_file(CONF).with_content(line) }
          end

          it { expect(chef_run).to start_service('dnf-automatic.timer') }
        else
          it 'refuses options EL8 ignores and names who set them' do
            expect { chef_run }.to raise_error(
              RuntimeError,
              /EL8 ignores: reboot = "when-needed" \(dnf_automatic_policy\[early\], dnf_automatic_policy\[late\]\); send_error_messages = true \(dnf_automatic_policy\[late\]\)/
            )
          end
        end
      end

      context 'without a schedule or header' do
        cached(:chef_run) do
          converge_delayed(ChefSpec::SoloRunner.new(p.merge(step_into: STEP_INTO)).converge('dnf-automatic-test::bare'))
        end

        it { expect(chef_run).to delete_osl_systemd_unit_drop_in('dnf-automatic').with(unit_name: 'dnf-automatic.timer') }
        it { expect(chef_run).to_not render_file(CONF).with_content(/generated by/) }
        it { expect(chef_run).to render_file(CONF).with_content(/^\[commands\]/) }
      end
    end
  end

  context 'a policy without a baseline' do
    cached(:chef_run) do
      converge_delayed(ChefSpec::SoloRunner.new(ALMA_10.merge(step_into: STEP_INTO)).converge('dnf-automatic-test::orphan'))
    end

    it { expect { chef_run }.to_not raise_error }
    it { expect(chef_run).to add_dnf_automatic_policy('orphan') }
    it { expect(chef_run).to apply_dnf_automatic_apply('default') }
    it { expect(chef_run).to_not install_package('dnf-automatic') }
    it { expect(chef_run).to_not create_template(CONF) }
    it { expect(chef_run).to_not start_service('dnf-automatic.timer') }
    it { expect(chef_run).to_not stop_service('dnf-automatic.timer') }
  end

  context 'a run that fails before a policy' do
    cached(:chef_run) do
      runner = ChefSpec::SoloRunner.new(ALMA_10.merge(step_into: STEP_INTO + %w(ruby_block)))
      begin
        runner.converge('dnf-automatic-test::failed')
      rescue RuntimeError => e
        @error = e
      end
      runner
    end

    it { expect { chef_run }.to_not raise_error }
    it { expect(chef_run).to configure_dnf_automatic('default') }
    it { expect(chef_run).to_not add_dnf_automatic_policy('held') }
    it { expect(chef_run).to apply_dnf_automatic_apply('default') }
    it { expect(chef_run.find_resource(:template, CONF)).to be_nil }
    it { expect(chef_run.find_resource(:service, 'dnf-automatic.timer')).to be_nil }
  end

  context 'two baselines' do
    cached(:chef_run) do
      converge_delayed(ChefSpec::SoloRunner.new(ALMA_10.merge(step_into: STEP_INTO)).converge('dnf-automatic-test::default', 'dnf-automatic-test::second'))
    end

    it do
      expect { chef_run }.to raise_error(RuntimeError, /only one baseline is allowed, dnf_automatic\[default\] is already declared/)
    end
  end
end
